"""The vault envelope's cross-language contract.

The vectors file is generated by ``@helio/core`` (Node/Web Crypto) and
committed; this suite replays it byte-for-byte with python-cryptography.
If either implementation drifts from the format, one of the two suites
breaks — that's the contract.
"""

from __future__ import annotations

import base64
import hashlib
import json
from pathlib import Path
from typing import Any

import pytest

from helio_intelligence.vault import (
    VaultDecryptError,
    VaultFormatError,
    VaultKeyUnknownError,
    decrypt_field,
    encrypt_field,
    is_envelope,
    key_fingerprint,
    parse_envelope,
)

VECTORS_FILE = (
    Path(__file__).parents[3] / "packages/core/tests/fixtures/crypto-envelope-vectors.json"
)
VECTORS: list[dict[str, Any]] = json.loads(VECTORS_FILE.read_text())

EXPECTED_ERRORS = {
    "fail_tag": VaultDecryptError,
    "fail_aad": VaultDecryptError,
    "fail_key": VaultKeyUnknownError,
    "fail_format": VaultFormatError,
}

# Deterministic, obviously-non-secret test keys (mirror the generator).
KEY = base64.b64encode(hashlib.sha256(b"helio-vault-test-key-py").digest()).decode()
OTHER_KEY = base64.b64encode(hashlib.sha256(b"helio-vault-test-key-py-2").digest()).decode()


def test_the_vector_file_covers_every_outcome() -> None:
    kinds = {vector["expect"] for vector in VECTORS}
    assert kinds == {"ok", "fail_tag", "fail_aad", "fail_key", "fail_format"}


@pytest.mark.parametrize("vector", VECTORS, ids=[v["description"] for v in VECTORS])
def test_node_written_vectors_replay(vector: dict[str, Any]) -> None:
    kwargs = {
        "organization_id": vector["organizationId"],
        "credential_id": vector["credentialId"],
        "field": vector["field"],
        "key_b64": vector["key"],
        "previous_key_b64": vector["previousKey"],
    }
    if vector["expect"] == "ok":
        assert decrypt_field(vector["envelope"], **kwargs) == vector["plaintext"]
    else:
        with pytest.raises(EXPECTED_ERRORS[vector["expect"]]):
            decrypt_field(vector["envelope"], **kwargs)


def test_python_round_trip_matches_the_format() -> None:
    envelope = encrypt_field(
        "groq-api-key-🔑",
        organization_id="org_py",
        credential_id="cred_py",
        field="apiKey",
        key_b64=KEY,
    )
    assert is_envelope(envelope)
    parsed = parse_envelope(envelope)
    assert parsed.fingerprint == key_fingerprint(KEY)
    assert len(parsed.iv) == 12 and len(parsed.tag) == 16
    assert (
        decrypt_field(
            envelope,
            organization_id="org_py",
            credential_id="cred_py",
            field="apiKey",
            key_b64=KEY,
        )
        == "groq-api-key-🔑"
    )


def test_aad_binds_org_credential_and_field() -> None:
    envelope = encrypt_field(
        "secret",
        organization_id="org_py",
        credential_id="cred_py",
        field="apiKey",
        key_b64=KEY,
    )
    for override in (
        {"organization_id": "org_other"},
        {"credential_id": "cred_other"},
        {"field": "other"},
    ):
        kwargs = {
            "organization_id": "org_py",
            "credential_id": "cred_py",
            "field": "apiKey",
            **override,
        }
        with pytest.raises(VaultDecryptError):
            decrypt_field(envelope, key_b64=KEY, **kwargs)


def test_rotation_accepts_the_previous_key_only_by_fingerprint() -> None:
    envelope = encrypt_field(
        "rotating",
        organization_id="org_py",
        credential_id="cred_py",
        field="apiKey",
        key_b64=KEY,
    )
    common = {"organization_id": "org_py", "credential_id": "cred_py", "field": "apiKey"}
    assert decrypt_field(envelope, key_b64=OTHER_KEY, previous_key_b64=KEY, **common) == "rotating"
    with pytest.raises(VaultKeyUnknownError):
        decrypt_field(envelope, key_b64=OTHER_KEY, **common)


def test_malformed_keys_and_envelopes_are_rejected() -> None:
    with pytest.raises(VaultFormatError):
        key_fingerprint("dG9vLXNob3J0")
    with pytest.raises(VaultFormatError):
        parse_envelope("enc:v2:aabbccdd:a:a:a")
    assert not is_envelope("not-an-envelope")
    assert not is_envelope(42)
