import { docs } from 'collections/server';
import { loader } from 'fumadocs-core/source';

// The content-source adapter: maps the `content/docs` collection onto URLs
// under `/docs`. `collections/server` is generated by `fumadocs-mdx`.
export const source = loader({
  baseUrl: '/docs',
  source: docs.toFumadocsSource(),
});
