#!/bin/sh
# Helio migrate-image entrypoint. Subcommands:
#   deploy  — wait for Postgres, apply migrations, sync the app-role password
#   seed    — load the idempotent demo workspace
#   status  — report migration state
#   rotate  — re-encrypt vault envelopes under the active HELIO_ENCRYPTION_KEY
set -eu
cd /app

BIN=./node_modules/.bin

if [ -z "${DATABASE_ADMIN_URL:-}" ]; then
  echo "DATABASE_ADMIN_URL is required" >&2
  exit 1
fi

wait_for_db() {
  attempts=0
  until node -e '
    const { Client } = require("pg");
    const client = new Client({ connectionString: process.env.DATABASE_ADMIN_URL });
    client.connect().then(() => client.end()).then(() => process.exit(0)).catch(() => process.exit(1));
  ' >/dev/null 2>&1; do
    attempts=$((attempts + 1))
    if [ "$attempts" -ge 60 ]; then
      echo "postgres never became reachable" >&2
      exit 1
    fi
    echo "waiting for postgres… ($attempts)"
    sleep 2
  done
}

sync_app_role_password() {
  # Closes the well-known dev password on the RLS app role. The value is
  # generated by the installer; single quotes are SQL-escaped defensively.
  if [ -n "${HELIO_APP_DB_PASSWORD:-}" ]; then
    escaped=$(printf %s "$HELIO_APP_DB_PASSWORD" | sed "s/'/''/g")
    printf "ALTER ROLE helio_app WITH PASSWORD '%s';" "$escaped" \
      | "$BIN/prisma" db execute --stdin
    echo "helio_app password synced"
  fi
}

command="${1:-deploy}"
echo "helio-migrate ${HELIO_VERSION:-dev} — $command"

case "$command" in
  deploy)
    wait_for_db
    "$BIN/prisma" migrate deploy
    sync_app_role_password
    ;;
  seed)
    wait_for_db
    "$BIN/tsx" prisma/seed.ts
    ;;
  status)
    wait_for_db
    "$BIN/prisma" migrate status
    ;;
  rotate)
    wait_for_db
    "$BIN/tsx" scripts/rotate-encryption-key.ts
    ;;
  *)
    exec "$@"
    ;;
esac
