{{- $root := . -}}
{{- range $name, $svc := .Values.services }}
{{- if $svc.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helio.fullname" $root }}-{{ $name }}
  labels:
    {{- include "helio.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  type: ClusterIP
  selector:
    {{- include "helio.selectorLabels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: http
      protocol: TCP
{{- end }}
{{- end }}
